### ISSUE TITLE
ModalPopup or BottomSheetPopup showing randomly on anyscreen. 

### ISSUE THREAD

**Issue by rajkapoordev** [GetStream/stream-chat-react-native#1283]
Hello @vishalnarkhede @madsroskar 
**Describe the bug**
Some strange modal showing randomly on any screen. I have attach the screenshots of inspect on that modal. It is something regarding to **AttacmentPickerBottomSheet**.

**Dev environment info**

- stream-chat-react-native version : ^4.3.1
- react-native version : 0.63.4
- only android devices 

**To Reproduce**
 The popup shown randomly on any screen.

**Expected behavior**
The popup should not shown on any random screens.

**Screenshots**
<img src="https://user-images.githubusercontent.com/11647774/163333481-c67174c8-c6b0-4316-bc2c-29a762e6d493.jpg" width="400" height="800">
</br>
</br>
<img src="https://user-images.githubusercontent.com/11647774/163333486-8621fa13-5f4b-45e0-9128-324d9e8eb9e5.jpg" width="400" height="800">

gz#21832

**Comment by santhoshvai** [comment]
hi @rajkapoordev, Thanks for filing this issue. I haven't been able to reproduce this.

is it possible for you to give us any clue about how to reproduce this? Also, It would be great if you can give us a repo where we can reproduce this.

**Comment by rajkapoordev** [comment]
@santhoshvai 
Don't have any clue but it appears when the keyboard is open or close.

**Comment by rajkapoordev** [comment]
@santhoshvai ,
Please check this
https://github.com/GetStream/stream-chat-react-native/issues/1179#issuecomment-1132889971

**Comment by vanGalilea** [comment]
Closing this is a copy of [issue](https://github.com/GetStream/stream-chat-react-native/issues/1179)

**Comment by santhoshvai** [comment]
> @santhoshvai , Please check this [#1179 (comment)](https://github.com/GetStream/stream-chat-react-native/issues/1179#issuecomment-1132889971)

Hey @rajkapoordev, This solution would have worked. But the same error could have happened when images were set. I found a race condition that would cause this issue. We have published a beta version `v4.5.1-beta.1` with the fix for this race condition. Could you please upgrade the library, test, and confirm with us?

**Comment by dariusmandres** [comment]
Unfortunately this is still an issue in `4.9.0`

**Comment by santhoshvai** [comment]
@dariusmandres Could you update the package `@gorhom/bottom-sheet` to the latest version and check again and report here please. We cannot reproduce it anymore after we updated it.

**Comment by dariusmandres** [comment]
@santhoshvai I tried it with `stream-chat-react-native@4.9.0` and `@gorhom/bottom-sheet@4.4.3`, which is the latest as of right now.

Although, for me this specifically happens in the `Channel` screen, using the `MessageInput` component. On Android, when tapping the input to type, the bottom sheet appears.

I have fixed it by manually applying this patch
```
diff --git a/node_modules/stream-chat-react-native-core/src/components/AttachmentPicker/AttachmentPicker.tsx b/node_modules/stream-chat-react-native-core/src/components/AttachmentPicker/AttachmentPicker.tsx
index c3992d5..bfe70cb 100644
--- a/node_modules/stream-chat-react-native-core/src/components/AttachmentPicker/AttachmentPicker.tsx
+++ b/node_modules/stream-chat-react-native-core/src/components/AttachmentPicker/AttachmentPicker.tsx
@@ -502,6 +502,8 @@ export const AttachmentPicker = React.forwardRef(
       [initialSnapPoint, finalSnapPoint],
     );
 
+    return null;
+
     return (
       <>
         <BottomSheet
```

**Comment by santhoshvai** [comment]
reopening this as it still happens according to multiple reports

**Comment by jayeshpurohit12** [comment]
@santhoshvai is there any solution of that yet ?

**Comment by santhoshvai** [comment]
Hi @jayeshpurohit12 @dariusmandres @rajkapoordev @GregAtFramework

We have published a new beta version  [v5.4.2-beta.2](https://github.com/GetStream/stream-chat-react-native/compare/v5.4.1...v5.4.2-beta.2) that aims to fix this issue. Could you please upgrade to this version and remove the patch package to `AttachmentPicker.tsx` (if any) and see if it's fixed?

I believe that this happens due to a race condition in the bottom sheet library. I was able to create a reproducible scenario and fix it there. But we want your feedback to confirm if this bug has been squashed out finally. It would be immensely helpful if you could test and report to us. 

also, many thanks for sharing the patch-package workaround @dariusmandres and @GregAtFramework!

**Comment by santhoshvai** [comment]
Closing this issue as it should be fixed as of version 5.4.2

**Comment by testanib** [comment]
> Closing this issue as it should be fixed as of version 5.4.2

The issue still occurs for me on 5.4.2

**Comment by santhoshvai** [comment]
@testanib 

could you send us a screenrecording or a reproducible repo please. We are not able to reproduce it anymore.
