### ISSUE TITLE
Image is not centered vertically on the preview

### ISSUE THREAD

**Issue by bmitioglov** [GetStream/stream-chat-react-native#1979]
**Describe the bug**
The app crashes from time to time. It's not happening if I remove OverlayProvider.

**Dev environment info** (please complete/provide the following information):

Package version: stream-chat-react-native 5.9.0
react-native 0.63.4
Device iOS 15.6

**To Reproduce**

1. Wrap the ChatScreen with OverlayProvider
```javascript
<OverlayProvider>
 <View style={{ flex: 1 }}>
          <Chat client={client} i18nInstance={streami18n}>
          <Channel channel={channel}
                   keyboardVerticalOffset={thread ? 120 : 90}
                   thread={thread}
                   threadList={!!thread}
                   MessageFooter={CustomMessageFooter}
          >
            {thread ? (
              <Thread />
            ) : (
              <>
                <MessageList onThreadSelect={setThread} />
                <MessageInput />
              </>
            )}
          </Channel>
        </Chat>
      </View>
</OverlayProvider>
```

2. Send a picture to the chat
3. Click on the picture in the chat to open image preview
4. The picture is displayed in the bottom of the screen, not in the center

**Expected behavior**
Image preview is centered vertically

**Additional context**
I was wrapping the whole app in OverlayProvider and in this case image preview works correctly but the app was crashing from time to time so I had to wrap only chat screen with OverlayProvider, that helped with the crashes.

**Screenshots**

![simulator screenshot](https://user-images.githubusercontent.com/1130073/219491036-f1b94cc7-2650-4ab8-9a51-b703d3fd3233.png)

**Comment by khushal87** [comment]
This seems to be an issue because of the bottom tabs. Hiding it should fix the issue, but let us see if there's an easy fix with the bottom tabs present.

**Comment by bmitioglov** [comment]
Hello,
here is my bottom tab configuration:

```javascript
const AppBottomTab = createBottomTabNavigator();

<AppBottomTab.Navigator theme={MyTheme} style={{ backgroundColor: '#fff' }}
                            initialRouteName='Home'
                            screenOptions={({ route }) => ({
                              tabBarShowLabel: false,
                              cardStyle: { backgroundColor: '#fff'},
                              headerShown: false,
                              tabBarStyle: {marginVertical: 5, backgroundColor: 'white', borderTopWidth: 0},
                              tabBarIcon: ({ focused, color, size }) => {
                                let iconName;
        
                                if (route.name === 'Home') {
                                  iconName = "dumbbell"
                                }
        
                                switch (route.name) {
                                  case 'Home':
                                    iconName = 'home-circle';
                                    return <MaterialCommunityIcons name={iconName} size={32} color={color} />
                                  case 'Analytics':
                                    return <MaterialIcons name="analytics" size={31} color={color} />
                                  case 'Measures':
                                    iconName = 'scale-bathroom'
                                    return <MaterialCommunityIcons name={iconName} size={29} color={color} />
                                  case 'Upgrade':
                                    iconName = 'crown'
                                    return <MaterialCommunityIcons name={iconName} size={31} color={color} />
                                  case 'Account':
                                    return <FontAwesome name="gear" size={31} color={color} />
                                    break;
                                  default:
                                    console.log("Wrong bottom tab name");
                                }
                                return <MaterialCommunityIcons name={iconName} size={30} color={color} />
                              },
                              tabBarActiveTintColor: '#0070f7',
                              tabBarInactiveTintColor: 'grey',
                            })}>
      <AppBottomTab.Screen name="Account">
        {screenProps => (
          <AccountStackNavigator updateAuthState={props.updateAuthState}/>
        )}
      </AppBottomTab.Screen>
      <AppBottomTab.Screen name="Analytics" component={AnalyticsStackNavigator} />
      <AppBottomTab.Screen name="Home" component={MainFlowStackNavigator} />
      <AppBottomTab.Screen name="Measures" component={MeasuresStackNavigator} />
      {props.userProps.isSubscribed ? null : <AppBottomTab.Screen name="Upgrade" component={UpgradeStackNavigator}/>}
      {/*<AppBottomTab.Screen name="Upgrade" component={UpgradeStackNavigator}/>*/}
    </AppBottomTab.Navigator>
```



As for the crashes, I already have an active ticket with Johann Eugen Kunzle support+id34372@getstream.zendesk.com

You can see the details here: https://github.com/GetStream/stream-chat-react-native/issues/1959, I can also send you a video of the bug if you need it.

**Comment by bmitioglov** [comment]
I tried to hide bottom tab navigator but that didn't help with images preview:

```javascript
const MainFlowStackNavigator = ({navigation, route}) => {
  
  React.useLayoutEffect(() => {
    const routeName = getFocusedRouteNameFromRoute(route);
    if (routeName === "ChatScreen"){
      navigation.setOptions({tabBarStyle: {display: 'none'}});
    }else {
      navigation.setOptions({tabBarStyle: {display: 'flex'}});
    }
  }, [navigation, route]);
  
  return (
    <MainFlowStack.Navigator
      screenOptions={{headerTitleAlign: 'left', shadowColor: 'transparent'}}
    >
...

```
![Simulator Screen Shot - iPhone 12 Pro - 2023-02-20 at 12 52 18](https://user-images.githubusercontent.com/1130073/220196970-c12966fe-15c2-4fe1-a397-cd0cb8ea0977.png)
![Simulator Screen Shot - iPhone 12 Pro - 2023-02-20 at 12 52 27](https://user-images.githubusercontent.com/1130073/220196999-d809fe86-4bbc-4e43-a5fd-5b9d9250f5bd.png)

**Comment by khushal87** [comment]
Can you remove the Header? Ideally, the bottom sheet that opens up for the ImageGallery is on the top layer of the entire screen, but that doesn't happen with you may be because of a different use case of react navigation. @bmitioglov

**Comment by bmitioglov** [comment]
When I remove the header it's still not centered but better than before. The thing is I need a header there because I need the '< Back' button
![Simulator Screen Shot - iPhone 12 Pro - 2023-02-22 at 17 04 19](https://user-images.githubusercontent.com/1130073/220799404-56eeb371-2288-4e77-ae27-726c8307b23c.png)

**Comment by bmitioglov** [comment]
without header chat looks like this:
![Simulator Screen Shot - iPhone 12 Pro - 2023-02-22 at 17 06 32](https://user-images.githubusercontent.com/1130073/220799543-2562983f-2476-47c3-84c2-71e9b8a3234c.png)

**Comment by khushal87** [comment]
Hello @bmitioglov, we are not able to reproduce this issue on our side with the setup we have.

To help you pinpoint this issue quickly, we would like to share a minimalistic repo where the problem is reproduced.

The fastest way to achieve that is with the following command to create a new RN project with Stream chat in it:
```
npx react-native init MyApp --template stream-chat-react-native-template
```

Please then share a Github repo with us, where we can explore the issue ourselves.

**Comment by bmitioglov** [comment]
Hi @khushal87,

I recreated the project from scratch with the following react versions:
    "react": "17.0.2",
    "react-native": "0.68.6"
I also removed all expo dependencies from the app.
And after that crash problem seemed to be resolved, so I moved OverlayProvider to the top of the component tree and the images are now centered too. 
The problem might be related to old Expo components left there after ejection (we ejected from Expo a long time ago) interfering somehow with new libraries. The Firebase SDK problem which we had https://github.com/invertase/react-native-firebase/issues/6933 was also resolved. My advice for anyone who wants to create a complex app - is don't use Expo :)

**Comment by vanGalilea** [comment]
@bmitioglov  thanks for getting back to us. Happy that you could solve this issue.
I'll be closing this issue for now.
Please don't hesitate to contact us in the future if this issue or any questions arise.
