### ISSUE TITLE
Error: 1st Example of React Native Tutorial

### ISSUE THREAD

**Issue by samzer** [GetStream/stream-chat-react-native#205]
**Describe the bug**
First example in the react-native tutorial is not working properly with the stream-chat-react-native library whereas the 2nd example which is Multiple conversations works properly

The only change to code that I made is renaming "stream-chat-expo" to "stream-chat-react-native";

The screenshot is attached below

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo)
stream-chat-react-native/
- react-native or expo version
react-native 0.60.5 and react-native 0.62
- Device/Emulator (android/ios) and OS version
iPhone 11 emulator with iOS13.3

**To Reproduce**

1. Start by getting the get stream react native example code ready which is for multiple conversations
2. Replace the App.js file with react native tutorial's first example code
3. Make sure to change the import from "stream-chat-expo" to "stream-chat-react-native"
4. Run the app

**Expected behavior**
The expectation was to see the chat message screen

**Screenshots**
<img width="419" alt="Screenshot 2020-04-23 at 9 16 41 PM" src="https://user-images.githubusercontent.com/1539703/80119780-c8049e80-85a7-11ea-9985-6bbe00155e13.png">

**Comment by samzer** [comment]
It seems to be working now although don't know why. Closing the issue.

**Comment by nemoNoboru** [comment]
I'm running into this issue too. Could you try to reproduce what you did to have it working?

**Comment by vishalnarkhede** [comment]
Hey @nemoNoboru I published a fix for this in 0.10.2. Can you please confirm is version of stream-chat-expo or stream-chat-react-native is 0.10.2?

**Comment by nemoNoboru** [comment]
Thanks for your quick reply!
Indeed, i was using the version `0.10.1` of the `stream-chat-react-native` package.
I updated it to 0.10.2 on the package.json and did a rm -rf node_modules && npm install
I can confirm that i'm using the version 0.10.2 now but the problem continues happening in android and ios. I'm running the metro bundler with the --reset-cache flag set.

**Comment by vishalnarkhede** [comment]
Hey @nemoNoboru I am looking into it. I will get back to you shortly :)

**Comment by vishalnarkhede** [comment]
@nemoNoboru Can you try removing `packge-lock.json` and then `npm install`

**Comment by nemoNoboru** [comment]
Hello @vishalnarkhede, I did just that. The problem is still there. i checked out my `package-lock.json` and it's like this
```
"stream-chat-react-native": {
      "version": "0.10.2",
      "resolved": "https://registry.npmjs.org/stream-chat-react-native/-/stream-chat-react-native-0.10.2.tgz",
      "integrity": "sha512-KW83e5bkeAvolH50aZWwIaTH4r8w2dkkUwuDiwO8zp1jgLc/I9kdUs4lf6z0gDkGyq0Ss/766tiYkHCmZgG+Tg==",
      "requires": {
        "es6-symbol": "^3.1.1",
        "stream-chat-react-native-core": "v0.10.2"
      }
    },
```
This is the code that i'm trying to run. Maybe I'm doing something wrong?
```
import React from 'react';

import { View, SafeAreaView, Text } from 'react-native';
import { StreamChat } from 'stream-chat';
import { Chat, Channel, MessageInput, MessageList } from 'stream-chat-react-native';

const chatClient = new StreamChat(
  <key>,
  <secret>,
);
const user = {
  id: 'john',
  name: 'John Doe',
  image: 'https://getstream.io/random_svg/?name=John',
};

function getChannel() {
  chatClient.setUser(
    user,
    <userToken>,
  );
  const channel = chatClient.channel('messaging', '123');
  return channel
}

const channel = getChannel()

export default () => {
  return (
    <SafeAreaView>
      <Chat client={chatClient}>
        <Channel channel={channel}>
          <View style={{ display: 'flex', height: '100%' }}>
            <MessageList/>
            <MessageInput />
          </View>
        </Channel>
      </Chat>
    </SafeAreaView>
  );
};
```
Also, the problem only happens if there is more than 1 message sent.

**Comment by nemoNoboru** [comment]
I don't have any idea how or why. But is fixed now. 
Thanks a lot for your help. You can close this issue :)
