### ISSUE TITLE
About weird line breaks in stream-chat-react-native

### ISSUE THREAD

**Issue by YohaanYoon** [GetStream/stream-chat-react-native#209]
**Describe the bug**
- When users write sentences with line breaks and special symbols (`!`, `?`, `.`, `,` and so on) in MessageInput component, it looks weird in MessageList Component as follows pics.

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native 0.10.1
- react-native 0.59.10
- both of android and ios

**To Reproduce**

1. write sentences with line breaks and special symbols (`!`, `?`, `.`, `,` and so on) in MessageInput component
2. looks weird in MessageList Component as follows pics.

![Image from iOS (7)](https://user-images.githubusercontent.com/6019966/81629403-04f0e200-943e-11ea-8aa7-168db87cb31e.jpg)
![Image from iOS (8)](https://user-images.githubusercontent.com/6019966/81629407-06220f00-943e-11ea-93e0-0c7981765298.jpg)

**Expected behavior**
- In case of stream-chat-react works in normal.

![스크린샷 2020-05-11 오후 5 50 16](https://user-images.githubusercontent.com/6019966/81629440-1a660c00-943e-11ea-8da5-a132bad5d708.png)

**Additional context**

**Screenshots**

**Comment by vishalnarkhede** [comment]
Hey @YohaanYoon please check `0.10.3`. We have published a fix for this :)

Let us know if it fixes your issue!!

**Comment by YohaanYoon** [comment]
I will check it out.

**Comment by vishalnarkhede** [comment]
@YohaanYoon Closing this for now. Please reopen if needed :)

**Comment by TobyColeman** [comment]
We're still experiencing this issue after upgrading to latest.

**Describe the bug**
- Same as OP

**Dev environment info (please complete/provide the following information):**
- stream-chat-react-native 0.15.0
- react-native 0.61.5
- ios

**To Reproduce**
- Same as OP

<img width="438" alt="Screenshot 2020-07-29 at 15 23 32" src="https://user-images.githubusercontent.com/8971184/88812647-e1714400-d1af-11ea-95c4-7ea4ea631463.png">
