### ISSUE TITLE
[🐛] MessageList is not updated even though messages received over WS

### ISSUE THREAD

**Issue by Jolville** [GetStream/stream-chat-react-native#2305]
## Issue

New messages (sometimes) aren't being rendered after reconnection events. We've looked into this on our side a fair bit and added some logging to check this wasn't a connection issue, and we can see `connection:onmessage() - onmessage callback` logs, but the message list component doesn't show them.

### Steps to reproduce

This doesn't happen consistently, but we were able to reproduce by

1. Creating a channel with two members
2. Opening the channel on two devices
3. Turning off mobile data on device A
4. Sending some messages from device B
5. Turning mobile data on device A back on, while simultaneously sending a message from device B.
6. Send more messages from device B

Occasionally, the messages sent from device B while device A was offline, as well as after it was back online, are never shown, until the component is unmounted/remounted by closing the screen.

### Expected behavior

Messages should be shown.

### Customization

<details><summary>Click To Expand</summary>
<p>

No custom components, but here is how we're rendering the channel:

```typescript jsx
<Chat client={client}>
  <Channel<StreamType>
    channel={channel}
    allowThreadMessagesInChannel={false}
    deletedMessagesVisibilityType="never"
    keyboardVerticalOffset={headerHeight}
    thread={thread}
    hasCommands={false}
    threadList={isInThreadView}
    messageActions={({ quotedReply }) => [quotedReply]}
    MessageFooter={MessageFooter}
    myMessageTheme={{
      colors: {
        grey_gainsboro: Colors.primary[500],
        black: Colors.secondary.lime[100],
      },
      overlay: {
        messageActions: {
          actionContainer: {
            backgroundColor: Colors.neutral[900],
            borderRadius: 16,
          },
        },
        reactionsList: {
          reactionList: {
            backgroundColor: Colors.neutral[900],
          },
        },
      },
      messageSimple: {
        card: {
          footer: {
            title: {
              color: Colors.primary[500],
            },
            description: {
              color: Colors.primary[500],
            },
          },
        },
        content: {
          containerInner: {
            borderColor: Colors.primary[500],
          },
          markdown: {
            text: {
              fontSize: FontSize.PARAGRAPH_S,
              fontFamily: FontFamily.ATLAS_GROTESK_LIGHT,
            },
            listItemBullet: {
              color: Colors.secondary.lime[100],
            },
            listItemNumber: {
              color: Colors.secondary.lime[100],
            },
          },
        },
      },
    }}
  >
    {isInThreadView ? (
      <Thread />
    ) : (
      <>
        <MessageList onThreadSelect={setThread} hideStickyDateHeader />
        <MessageInput
          giphyActive={false}
          additionalTextInputProps={{
            selectionColor: Colors.primary[300],
          }}
        />
      </>
    )}
  </Channel>
</Chat>
```
</p>
</details>

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
	"react-native": "0.71.14",
    "stream-chat": "~8.13.1",
    "stream-chat-expo": "^5.19.3",
    "stream-chat-react-native-core": "^5.19.3"
}
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [x] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `stream-chat-react-native-core@5.19.3`
- Device/Emulator info:
  - [x] I am using a physical device
  - iOS/17.0.2

</p>
</details>

### Additional context

We're also seeing some `connection:_errorFromWSEvent() - WS failed with code 1006`/`connection:_errorFromWSEvent() - WS failed with code undefined` logs from our customers around the same time they were reporting this issue (the connection does seem to re-establish fine though)

### Screenshots

N./A

---

**Comment by khushal87** [comment]
Hey @Jolville, is this working fine now?

**Comment by Jolville** [comment]
@khushal87 sorry this was closed automatically after I referenced it in a PR in one a private repo.

I've just bumped our stream package in the hopes that its fixed by https://github.com/GetStream/stream-chat-react-native/pull/2479 - will give it a test and get back to you

**Comment by khushal87** [comment]
Yes, please give it a look and let us know. Thanks 😄

**Comment by khushal87** [comment]
Hey @Jolville, can this be closed?

**Comment by abulnes-designli** [comment]
Hi, I'm using version `^5.27.1,`, and the problem is still appearing; the messages are shown after I click on the go-to last message button.

**Comment by fgauna12** [comment]
I've been chasing this issue after my users reported messages not being received. 

I can confirm it happens to me, too. Version `5.33.1` of the Expo SDK.

For me, 

When I receive a new message after it is reconnected, it doesn't show there are new messages or the "jump to the latest message" button. I have to scroll up to force getting the latest messages, and then they show up.

**Comment by fgauna12** [comment]
Updated, here's more specific reproduction steps because it was elusive. 

- Creating a channel with two members
- Opening the channel on two devices
- Turning off mobile data and WIFI on device A
- Sending some messages from device B
- Locking device B
- Turning mobile data and WIFI on device A back on
- Observe that new messages only appear on device A if you forcefully scroll down or go to the channel list and return to the chat.

**Comment by isekovanic** [comment]
Hi @fgauna12 , are you by any chance using `initialScrollToFirstUnreadMessage` on the `Channel` component ? We've noticed some weird behaviour whenever there are a lot of messages and you scroll to the first unread one, but other than that particular scenario I cannot reproduce this at all; after having followed your steps exactly. It's weird to me that 

Pretty sure that's exactly what happens on @abulnes-designli 's side too (since the scroll to bottom indicator is shown).

**Comment by fgauna12** [comment]
@isekovanic No I am not setting `initialScrollToFirstUnreadMessage`. I am loading the component around a message on occasion using the channel context, but outside of this scenario. 

```
            channelContext?.loadChannelAroundMessage({messageId: messageId});
```

I have tried upgrading to the latest version and the same still occurred.

**Comment by pfcodes** [comment]
Reports of users not receiving messages brought me here too. Sometimes users are forced to refresh to see new messages. It’s not everytime and not easily reproducible.

**Comment by i-am-different** [comment]
I work with @Jolville and I used these steps to reproduce the issue. I can consistently reproduce the issue by following the instructions that he provided. 

![Simulator Screenshot - iPhone 15 Pro - 2024-11-21 at 16 31 09](https://github.com/user-attachments/assets/be533b81-2322-4cf2-8e61-5cf4b1da80a1)

And these are the logs that accompany the error state:

<img width="883" alt="image" src="https://github.com/user-attachments/assets/c2111582-416a-4708-9fbf-04f1e507df58">
<img width="883" alt="image" src="https://github.com/user-attachments/assets/1c38eae7-d6ff-4282-8d6d-c4e085fd47f2">

**Comment by isekovanic** [comment]
Hi all, just a brief update: after wrestling with finding a way to reproduce this for quite some time I was finally able to find a reliable way to do so. 

Please stay tuned, we're working on finding the root cause for this and fixing it.

Just wanted to let everyone know.

**Comment by fgauna12** [comment]
@isekovanic Can you share your reproduction steps?

**Comment by isekovanic** [comment]
They should be explained [here](https://github.com/GetStream/stream-chat-react-native/pull/2807), let me know if you need me to elaborate deeper.

**Comment by khushal87** [comment]
Hello guys, is this still an issue with our recent versions of the SDK? If not, can we close it? We are not able to reproduce it anymore on our side.

**Comment by khushal87** [comment]
Please upgrade to the latest of our SDK and let us know if its still and issue with you all. We will be happy to look into it. Until then I will close it.
