### ISSUE TITLE
Version 1.3.2 - Keyboard is glitching - jumping, close does not work and send button needs to be tapped 3-4 times to send message, frame rates on JS thread drop to negatives when trying to use keyboard inside a channel.

### ISSUE THREAD

**Issue by thegitparticle** [GetStream/stream-chat-react-native#374]
**Describe the bug**
1) After upgrading to 1.3.2; the keyboard in glitching really bad. Isn't this supposed to be solved with the latest upgrades to the library??? When opening it pushes the input box to the top with huge gap in between. And while closing keyboard, it keeps jumping, and sometimes need to try closing it 3-4 times to close. 

2) The send button needs to be tapped 3-4 times to send the message. It's very unresponsive. 

3) Need to tap the InputBox many times to trigger the keyboard open.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo) - 1.3.2
- react-native or expo version - RN version 0.63.2
- Device/Emulator (android/ios) and OS version - Running on Android device - tried on Android 8, 9, 10 - same results. 

**To Reproduce**
Steps to reproduce the behavior: Using Default Channel -<Channel client={client} channel={channel}> and default MessageInput imported from this library; without any keyboard settings.

Let me know if any more details are needed to understand this issue.

gz#6472

**Comment by vishalnarkhede** [comment]
Hey @thegitparticle can you please try the following solution?

```js
import { KeyboardCompatibleView } from 'stream-chat-react-native'

// Define a custom keyboard view
const CustomKeyboardCompatibleView = ({children}) => (
    <KeyboardCompatibleView
      // You will need to fine-tune following keyboardVerticalOffset
      // as per your app UI
      // For iOS - its the height of your input box
      // For android - its some negative number, 
      keyboardVerticalOffset={Platform.OS === 'ios' ? 66.5 : -200}
      behavior={Platform.OS === 'ios' ? 'padding' : 'position'}>
      {children}
    </KeyboardCompatibleView>
  );

// And then use it in channel component
<Channel KeyboardCompatibleView={CustomKeyboardCompatibleView}>
      ...
</Channel>
```

Please let me know if it fixes the issue.

**Comment by thegitparticle** [comment]
This is better in terms of not making the keyboard jump too much. 

But 1) Send button issue still exists of course; 2) And the text of the message already sent stays in the input box sometimes even after the message sent appearing in the message list. Need to delete it all if need to type another message. 
Also, the JS thread is still hitting negatives when using Chat channel - scroll and all work fine, it's just when keyboard, sending is triggered, the frame rates drop and kind of freezes the app for seconds.

**Comment by thegitparticle** [comment]
This is better in terms of not making the keyboard jump too much. 

But 1) Send button issue still exists of course; 2) And the text of the message already sent stays in the input box sometimes even after the message sent appearing in the message list. Need to delete it all if need to type another message. 
Also, the JS thread is still hitting negatives when using Chat channel - scroll and all work fine, it's just when keyboard, sending is triggered, the frame rates drop and kind of freezes the app for seconds.

**Comment by vishalnarkhede** [comment]
@thegitparticle can you share some code around chat components?

**Comment by thegitparticle** [comment]
`
```
<Chat client={client} style={theme}>
          <Channel
            client={client}
            channel={channel}
            KeyboardCompatibleView={CustomKeyboardCompatibleView}>
            <View
              style={{
                display: 'flex',
                height: '100%',
              }}>
              <MessageList
                Message={MessageNew}
                DateSeparator={DateSeparator}
                EventIndicator={EventView}
                onThreadSelect={(thread) => {
                  triggerReply(thread, channel.id, client);
                }}
              />
              <MessageInput
                actionSheetStyles={actionsheetStyles}
                additionalTextInputProps={additionalTextInputProps}
              />
            </View>
          </Channel>
        </Chat>
```
`

`
```
const MessageNew = (props) => {
    if (props.message.deleted_at) {
      return null;
    }
    return (
      <MessageSimple
        {...props}
        forceAlign="left"
        ReactionList={null}
        actionSheetStyles={actionsheetStylesActions}
      />
    );
  };
```
`

**Comment by vishalnarkhede** [comment]
Hey @thegitparticle code seems to be fine. Can you also please try production build?

**Comment by vishalnarkhede** [comment]
Also do you see this issue on iOS as well?

**Comment by thegitparticle** [comment]
Tried it on Android 10, 9 and 8 - bundled app, not in debug mode. 

The keyboard jumping is not happening. It's smooth, input taking is also much better than before. Although, still not as smooth. But now, there is white splash which appears when keyboard opens and closes. Is there any way to make the splash dark at-least? My app is dark mode and it hurts eyes when that splash occurs. 

But the send button still is very un responsive. It takes 3-4 secs and sometimes multiple taps to get triggered.

**Comment by vishalnarkhede** [comment]
@thegitparticle can you please share some screenrecording, just to make sure I understand the issue correctly? You can share the link here or send it on support@getstream.io if you have any privacy issue.

**Comment by thegitparticle** [comment]
@vishalnarkhede Link: https://ufile.io/4zbnhmxv

**Comment by thegitparticle** [comment]
@vishalnarkhede any update on the Send button issue?

**Comment by thegitparticle** [comment]
@vishalnarkhede any update?

**Comment by vishalnarkhede** [comment]
Hey @thegitparticle sorry for delays. I was busy with some other things. I will take a look at this tomorrow morning and get back!

**Comment by thegitparticle** [comment]
@vishalnarkhede Our launch is being delayed because of this, please get back soon.

**Comment by vishalnarkhede** [comment]
@thegitparticle We are trying our best to reproduce the issue mentioned here. Can you also share the code for all the rest of the components - DateSeparator, EventView, additionalTextInputProps, actionsheetStyles

**Comment by thegitparticle** [comment]
Date Seperator:

```
import React from 'react';
import {View, Text, StyleSheet} from 'react-native';
import moment from 'moment';

export const DateSeparator = ({message}) => {
  return (
    <View style={styles.container}>
      <Text style={styles.date}>{moment(message.date).format('dddd')}</Text>
      <View style={styles.line} />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flexDirection: 'column',
    marginBottom: 10,
    marginTop: 10,
  },
  date: {
    fontWeight: 'normal',
    paddingBottom: 5,
    fontSize: 9,
    color: '#DDDDDD70',
  },
  line: {
    flex: 1,
    height: 0.5,
    backgroundColor: '#181818',
  },
});
```

```
const additionalTextInputProps = {
    placeholderTextColor: 'rgba(255, 255, 255, 0.3)',
    placeholder: 'Type something fun.....',
  };
```

```
const actionsheetStyles = {
    body: {
      backgroundColor: '#181818',
    },
    titleBox: {
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#181818',
    },
    titleText: {
      color: '#fff',
      fontSize: 14,
    },
    buttonBox: {
      height: 50,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#181818',
    },
    buttonText: {
      fontSize: 18,
      color: '#fff',
    },
  };

```

Let me know if any more is needed.

**Comment by vishalnarkhede** [comment]
@thegitparticle EventView?

**Comment by thegitparticle** [comment]
```
const EventView = () => {
    return <></>;
  };

```

**Comment by thegitparticle** [comment]
@vishalnarkhede any update on this?

**Comment by vishalnarkhede** [comment]
Hey @thegitparticle I have published a dev release. Can you please try `stream-chat-react-native@1.3.4-dev.0` and see if it fixes the UX issues with send message functionality

**Comment by thegitparticle** [comment]
Regular yarn install does or should I change it in all imports as welll?

**Comment by vishalnarkhede** [comment]
You will need to manually change it in your package.json.

**Comment by thegitparticle** [comment]
It still persists. Although this time multiple taps are not needed as far as I checked, but once you tap it disappears takes 2-3 secs to appear in the sent list.

**Comment by thegitparticle** [comment]
this is fixed and keyboard is smooth when downgraded to 1.20.0. But still persists on above versions as far as the tests I've done.

**Comment by vishalnarkhede** [comment]
Hey glad that issue is fixed. I will still recommend you to upgrade to 1.3.4 and test again. Closing the issue for now, please reopen if you have more questions.
